name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v0
      with:
        # workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        token_format: 'access_token'
        access_token_lifetime: 300s
    - name: "authentication to Docker repositories "
      run: |
          gcloud auth configure-docker
    - name: docker image list
      run: docker image ls 
    - name: Build the Docker image
      run: docker build .  --file dockerfile --tag docker-image:my-first-image
      working-directory: ./docker-image
    - name: docker image list
      run: docker image ls 
    - name : retag
      run: docker image tag docker-image:my-first-image gcr.io/dssrc-test-project-367514/docker-image:my-first-image
    - name: docker image list
      run: docker image ls 
    - name: docker push
      run: docker push gcr.io/dssrc-test-project-367514/docker-image:my-first-image
    
    # - name: docker image access
    #   run: chmod -v 755 /var/lib/docker
    # - name: docker image save
    #   run: docker save gcrimage > /tmp/gcrimage.tar
    # - name: docker image load
    #   run: docker load -i /tmp/gcrimage.tar
    # - name: docker image permission
    #   run: chmod -v 755 /tmp/gcrimage.tar
    # - name: docker copy
    #   run: sudo docker cp /temp/gcrimage.tar ~/
    # - name: docker image info
    #   run: docker info
 

    # - name: Push to GCR Repo
    #   run: gcloud container images list-tags gcr.io/dssrc-test-project-367514/my-docker-image  


